wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
batch_size:
  desc: null
  value: 6
lr:
  desc: null
  value: 0.05
momentum:
  desc: null
  value: 0.9
random_seed:
  desc: null
  value: 99
validation_percentage:
  desc: null
  value: 0.2
